version: "2"
services:
    nginx:
        image: tutum/nginx
        ports:
            - "80:80"
        links:
            - phpfpm
        depends_on:
            - phpfpm
        volumes:
            - ./nginx/default:/etc/nginx/sites-available/default
            - ./nginx/default:/etc/nginx/sites-enabled/default
            - ./logs/nginx-access.log:/var/log/nginx/access.log
            - ./logs/nginx-error.log:/var/log/nginx/error.log

    phpfpm:
        image: php:fpm
        ports:
            - "9000:9000"
        volumes:
            - ./:/usr/share/nginx/catho
        links:
            - memcached
        depends_on:
            - memcached

    memcached:
        image: memcached
        ports:
            - "11211:11211"
