version: "2"
services:
    nginx:
        image: tutum/nginx
        ports:
            - "80:80"
        links:
            - phpfpm
        depends_on:
            - phpfpm
        volumes:
            # config file
            - ./nginx/default:/etc/nginx/sites-available/default
            - ./nginx/default:/etc/nginx/sites-enabled/default
            #static files
            - ./public:/usr/share/nginx/catho/public

    phpfpm:
        image: felipecwb/php
        volumes:
            #php source
            - ./:/home/catho
        links:
            - memcached
        depends_on:
            - memcached

    memcached:
        image: memcached
